[sel Num_Menu]
[f 0 5 -258][f 2 1]0[e]
[f 0 5 -258][f 2 1]1[e]
[f 0 5 -258][f 2 1]2[e]
[f 0 5 -258][f 2 1]3[e]
[f 0 5 -258][f 2 1]4[e]
[f 0 5 -258][f 2 1]5[e]
[f 0 5 -258][f 2 1]6[e]
[f 0 5 -258][f 2 1]Next[e]

[sel Num_Menu2]
[f 0 5 -258][f 2 1]7[e]
[f 0 5 -258][f 2 1]8[e]
[f 0 5 -258][f 2 1]9[e]
[f 0 5 -258][f 2 1]Back[e]

[sel OnOff]
[f 0 5 -258][f 2 1]On[e]
[f 0 5 -258][f 2 1]Off[e]

[msg MSG_1]
[f 0 5 -258][f 2 1]1 Digit[n][f 1 1][e]

[msg MSG_2]
[f 0 5 -258][f 2 1]2 Digits[n][f 1 1][e]

[msg MSG_3]
[f 0 5 -258][f 2 1]3 Digits[n][f 1 1][e]

[msg MSG_4]
[f 0 5 -258][f 2 1]4 Digits[n][f 1 1][e]

[msg MSG_5]
[f 0 5 -258][f 2 1]5 Digits[n][f 1 1][e]