[msg LMAP_DUMMY]
[f 0 5 -258][f 2 1]クマ[n][e]

[msg HELP_GO_STATION]
[f 0 5 -258][f 2 1]If you go to Okina, night will fall when[n]you leave.[n][f 1 1][e]

[msg MSG_GO_STATION]
[f 0 5 -258][f 2 1]> Spend time in Okina until evening?[n][f 1 1][e]

[sel SEL_GO_STATION]
[f 0 5 -258][f 2 1]Go to Okina[e]
[f 0 5 -258][f 2 1]Cancel[e]

[msg MSG_GO_SEA]
[f 0 5 -258][f 2 1]> Spend time sea fishing until evening?[n][f 1 1][e]

[sel SEL_GO_SEA]
[f 0 5 -258][f 2 1]Yes[e]
[f 0 5 -258][f 2 1]No[e]

[msg School_Text]
[f 0 5 -258][f 2 1]Yasogami High[n][f 1 1][e]

[sel School]
[f 0 5 -258][f 2 1]Classroom Building[e]
[f 0 5 -258][f 2 1]Practice Building[e]
[f 0 5 -258][f 2 1]Class 2-2[e]
[f 0 5 -258][f 2 1]Cancel[e]

[sel ClassroomBuilding]
[f 0 5 -258][f 2 1]Classroom Building, 1F[e]
[f 0 5 -258][f 2 1]Classroom Building, 2F[e]
[f 0 5 -258][f 2 1]Classroom Building, 3F[e]
[f 0 5 -258][f 2 1]Roof[e]
[f 0 5 -258][f 2 1]Cancel[e]

[sel PracticeBuilding]
[f 0 5 -258][f 2 1]Practice Building, 1F[e]
[f 0 5 -258][f 2 1]Practice Building, 2F[e]
[f 0 5 -258][f 2 1]Cancel[e]

[msg Street_Text]
[f 0 5 -258][f 2 1]Town of Inaba[n][f 1 1][e]

[sel ShoppingDistrictDay]
[f 0 5 -258][f 2 1]Shopping District, South[e]
[f 0 5 -258][f 2 1]Shopping District, North[e]
[f 0 5 -258][f 2 1]Shrine[e]
[f 0 5 -258][f 2 1]Daidara Metalworks[e]
[f 0 5 -258][f 2 1]Shiroku Store[e]
[f 0 5 -258][f 2 1]Velvet Room[e]
[f 0 5 -258][f 2 1]Cancel[e]

[sel FloodPlain]
[f 0 5 -258][f 2 1]Flood Plain[e]
[f 0 5 -258][f 2 1]Riverbank[e]
[f 0 5 -258][f 2 1]Cancel[e]

[msg FloodPlain_Text]
[f 0 5 -258][f 2 1]Samegawa Flood Plain[n][f 1 1][e]

[msg MSG_MARIE_VELVET_IN [Marie]]
[f 0 5 -258][f 2 1][f 4 6 60 1 0 1]Oh, you're going in? Then I'll go, too.[n][f 1 1][e]

[msg MARGARET_GOJITUDAN_01 [Margaret]]
[f 0 5 -258][f 2 1][f 4 6 34 1 0 1]Oh... Hello.[n][f 1 1][e]

[msg MSG_0320_AFTER_E428002]
[f 0 5 -258][f 2 1]> It began raining...[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED]
[f 0 5 -258][f 2 1]> There's no reason for you to be here...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO]
[f 0 5 -258][f 2 1]> You feel that you haven't finished[n]saying farewell to everyone...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Return home and prepare for tomorrow...?[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL]
[f 0 5 -258][f 2 1]> You feel that you have said farewell to[n]everyone precious to you.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Return home and prepare for tomorrow...?[n][f 1 1][e]

[msg MSG_0320_RETURN_HOME]
[f 0 5 -258][f 2 1]> Return home and prepare for tomorrow...?[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO2]
[f 0 5 -258][f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You have yet to speak with some of[n]the people who are close to you.[n][f 1 1][e]

[msg MSG_0320_RETURN_HOME2]
[f 0 5 -258][f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> It's time for you to go back home to[n]prepare for tomorrow...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL3]
[f 0 5 -258][f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You now have said goodbye to everyone[n]who is close to you.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Is there something that you still[n]have to do here...?[n][f 1 1][e]

[msg MSG_0417_VELVET_DONOTENT]
[f 0 5 -258][f 2 1]> You have no need to enter here...[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED3]
[f 0 5 -258][f 2 1]> There's no reason for you to be here...[n][f 1 1][e]

[msg MSG_0320_DOUJIMA_SEARCH]
[f 0 5 -258][f 2 1]> You should look for Dojima and Nanako...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL2]
[f 0 5 -258][f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You now have said goodbye to everyone[n]who is close to you.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> It's time for you to go back home to[n]prepare for tomorrow...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_YUKI]
[f 0 5 -258][f 2 1]> Come to think of it, you have yet[n]to say goodbye to Yukiko...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit the Amagi Inn...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You can get to the [f 0 1 2]Amagi Inn[n]from the bus stop at the shopping district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_ENGE]
[f 0 5 -258][f 2 1]> Come to think of it, you have yet[n]to say goodbye to Yumi...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit the drama club...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> [f 0 1 2]The drama club is in the meeting[n]room on the first floor of the[n]Practice Building[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_SUIS]
[f 0 5 -258][f 2 1]> Come to think of it, you have yet[n]to say goodbye to Ayane...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit the band room...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> [f 0 1 2]The band meets in the music room[n]on the first floor of the[n]Practice Building[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_BASK]
[f 0 5 -258][f 2 1]> Come to think of it, you have yet[n]to say goodbye to Kou and Daisuke...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You remember how you went to Aiya[n]with them...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit [f 0 1 2]Aiya in the[n]shopping district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_SOCC]
[f 0 5 -258][f 2 1]> Come to think of it, you have yet[n]to say goodbye to Daisuke and Kou...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You remember how you went to Aiya[n]with them...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit [f 0 1 2]Aiya in the[n]shopping district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_KITU]
[f 0 5 -258][f 2 1]> Come to think of it, what has happened[n]to the fox...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should summon the fox at the[n][f 0 1 2]main building of the shrine[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_NAOT]
[f 0 5 -258][f 2 1]> Come to think of it, you have yet[n]to say goodbye to Naoto...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Naoto was always standing around at the[n][f 0 1 2]first floor hallway of the school's[n]Classroom Building[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_ROUH]
[f 0 5 -258][f 2 1]> Come to think of it, what has happened[n]to Hisano...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit the place where you[n]spent time with her...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Hisano was always standing around the[n][f 0 1 2]riverbank of Samegawa Flood Plain[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_HAHA]
[f 0 5 -258][f 2 1]> Come to think of it, you have yet[n]to say goodbye to Eri...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit the hill where you[n]met her...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You can get to the [f 0 1 2]hill from the[n]bus stop at the shopping district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_NURS]
[f 0 5 -258][f 2 1]> Come to think of it, what has happened[n]to Sayoko...?[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit the place where you spent[n]time with her...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You can get to [f 0 1 2]Inaba Municipal[n]Hospital from the bus stop at the shopping[n]district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_YOUS]
[f 0 5 -258][f 2 1]> Come to think of it, you have yet[n]to say goodbye to Yosuke and Teddie...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit the [f 0 1 2]Junes'[n]food court[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_DOUJ]
[f 0 5 -258][f 2 1]> You should say hello to Dojima...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit the[n][f 0 1 2]Dojima residence[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_NANA]
[f 0 5 -258][f 2 1]> You should say hello to Nanako...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit the[n][f 0 1 2]Dojima residence[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_DOUJ2]
[f 0 5 -258][f 2 1]> You should say hello to[n]Dojima and Nanako...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You should visit the[n][f 0 1 2]Dojima residence[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_AI]
[f 0 5 -258][f 2 1]> Come to think of it, you have yet[n]to say goodbye to Ai...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Ai was always standing around at the[n][f 0 1 2]first floor hallway of the school's[n]Classroom Building[f 0 1 0]...[n][f 1 1][e]

[msg EQUIP_SHOP_STOP]
[f 2 1]> A fierce-looking man is single-mindedly[n]pounding on something in the back of the[n]store...[n][f 1 1][e]
[f 2 1]> You decide not to enter...[n][f 1 1][e]

[msg EQUIP_SHOP_CLOSED]
[f 2 1]> The store has closed for today...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL_2]
[f 0 5 65278][f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You now have said goodbye to everyone[n]who is close to you.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> Is there something that you still[n]have to do here...?[n][f 1 1][e]

[msg MSG_ITEMSHOP_0411]
[f 2 1]> A variety of products lines the[n]shelves...[n][f 1 1][e]
[f 2 1]> A friendly-looking old lady sits behind[n]the counter...[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED2]
[f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO_3]
[f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 2 1]> You have yet to speak with some of[n]the people who are close to you.[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL_4]
[f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 2 1]> You now have said goodbye to everyone[n]who is close to you.[n][f 1 1][e]
[f 2 1]> It's time for you to go back home to[n]prepare for tomorrow...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL_5]
[f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 2 1]> You now have said goodbye to everyone[n]who is close to you.[n][f 1 1][e]
[f 2 1]> Is there something that you still[n]have to do here...?[n][f 1 1][e]

[sel YESNO_SEL top]
[f 0 5 65278][f 2 1]Yes[e]
[f 0 5 65278][f 2 1]No[e]

[msg MSG_0320_GO_HOME_COMU_NO_2]
[f 0 5 65278][f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You have yet to speak with some of[n]the people who are close to you.[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL_3]
[f 0 5 65278][f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You now have said goodbye to everyone[n]who is close to you.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> It's time for you to go back home to[n]prepare for tomorrow...[n][f 1 1][e]
