[sel StreetNight]
[f 0 5 -258][f 2 1]Shopping District[e]
[f 0 5 -258][f 2 1]Shrine[e]
[f 0 5 -258][f 2 1]Go back home[e]
[f 0 5 -258][f 2 1]Cancel[e]

[sel ShoppingDistrict]
[f 0 5 -258][f 2 1]Shopping District, South[e]
[f 0 5 -258][f 2 1]Shopping District, North[e]
[f 0 5 -258][f 2 1]Shiroku Pub[e]
[f 0 5 -258][f 2 1]Velvet Room[e]
[f 0 5 -258][f 2 1]Cancel[e]

[msg MSG_MARIE_VELVET_IN [Marie]]
[f 0 5 -258][f 2 1][f 4 6 60 1 0 1]Oh, you're going in? Then I'll go, too.[n][f 1 1][e]

[msg MARGARET_GOJITUDAN_01 [Margaret]]
[f 0 5 -258][f 2 1][f 4 6 34 1 0 1]Oh... Hello.[n][f 1 1][e]

[msg MSG_0320_AFTER_E428002]
[f 0 5 -258][f 2 1]> It began raining...[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED]
[f 0 5 -258][f 2 1]> There's no reason for you to be here...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO]
[f 0 5 -258][f 2 1]> You feel that you haven't finished[n]saying farewell to everyone...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Return home and prepare for tomorrow...?[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL]
[f 0 5 -258][f 2 1]> You feel that you have said farewell to[n]everyone precious to you.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Return home and prepare for tomorrow...?[n][f 1 1][e]

[msg MSG_0320_RETURN_HOME]
[f 0 5 -258][f 2 1]> Return home and prepare for tomorrow...?[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO2]
[f 0 5 -258][f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You have yet to speak with some of[n]the people who are close to you.[n][f 1 1][e]


[msg MSG_0320_RETURN_HOME2]
[f 0 5 -258][f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> It's time for you to go back home to[n]prepare for tomorrow...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL3]
[f 0 5 -258][f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You now have said goodbye to everyone[n]who is close to you.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> Is there something that you still[n]have to do here...?[n][f 1 1][e]

[msg MSG_0417_VELVET_DONOTENT]
[f 0 5 -258][f 2 1]> You have no need to enter here...[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED3]
[f 0 5 -258][f 2 1]> There's no reason for you to be here...[n][f 1 1][e]

[msg MSG_0320_DOUJIMA_SEARCH]
[f 0 5 -258][f 2 1]> You should look for Dojima and Nanako...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL2]
[f 0 5 -258][f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 0 5 -258][f 2 1]> You now have said goodbye to everyone[n]who is close to you.[n][f 1 1][e]
[f 0 5 -258][f 2 1]> It's time for you to go back home to[n]prepare for tomorrow...[n][f 1 1][e]
