[msg HANG_OUT_MSG]
[f 0 5 -258][f 2 1]Who do you want to see?[n][f 1 1][e]

[sel HANG_OUT_SEL]
[f 0 5 -258][f 2 1]Adachi (Rank [f 2 4 16][f 2 4 0])[e]
[f 0 5 -258][f 2 1]Ai (Rank [f 2 4 17][f 2 4 1])[e]
[f 0 5 -258][f 2 1]Ayane (Rank [f 2 4 19][f 2 4 3])[e]
[f 0 5 -258][f 2 1]Chie (Rank [f 2 4 18][f 2 4 2])[e]
[f 0 5 -258][f 2 1]Chie (Scooter)[e]
[f 0 5 -258][f 2 1]Daisuke (Rank [f 2 4 29][f 2 4 13])[e]
[f 0 5 -258][f 2 1]Dojima (Rank [f 2 4 20][f 2 4 4])[e]
[f 0 5 -258][f 2 1]Eri (Rank [f 2 4 20][f 2 4 4])[e]
[f 0 5 -258][f 2 1]Fox (Rank [f 2 4 27][f 2 4 11])[e]
[f 0 5 -258][f 2 1]Hisano (Rank [f 2 4 21][f 2 4 5])[e]
[f 0 5 -258][f 2 1]Kanji (Rank [f 2 4 22][f 2 4 6])[e]
[f 0 5 -258][f 2 1]Kanji (Scooter)[e]
[f 0 5 -258][f 2 1]Kou (Rank [f 2 4 29][f 2 4 13])[e]
[f 0 5 -258][f 2 1]Marie (Rank [f 2 4 23][f 2 4 7])[e]
[f 0 5 -258][f 2 1]Nanako (Rank [f 2 4 21][f 2 4 5])[e]
[f 0 5 -258][f 2 1]Naoki (Rank [f 2 4 24][f 2 4 8])[e]
[f 0 5 -258][f 2 1]Naoto (Rank [f 2 4 25][f 2 4 9])[e]
[f 0 5 -258][f 2 1]Naoto (Scooter)[e]
[f 0 5 -258][f 2 1]Rise (Rank [f 2 4 26][f 2 4 10])[e]
[f 0 5 -258][f 2 1]Rise (Scooter)[e]
[f 0 5 -258][f 2 1]Sayoko (Rank [f 2 4 27][f 2 4 11])[e]
[f 0 5 -258][f 2 1]Shu (Rank [f 2 4 28][f 2 4 12])[e]
[f 0 5 -258][f 2 1]Teddie (Scooter)[e]
[f 0 5 -258][f 2 1]Yosuke (Rank [f 2 4 30][f 2 4 14])[e]
[f 0 5 -258][f 2 1]Yosuke (Scooter)[e]
[f 0 5 -258][f 2 1]Yukiko (Rank [f 2 4 31][f 2 4 15])[e]
[f 0 5 -258][f 2 1]Yukiko (Scooter)[e]
[f 0 5 -258][f 2 1]Yumi (Rank [f 2 4 19][f 2 4 3])[e]
[f 0 5 -258][f 2 1]Someone else[e]
[f 0 5 -258][f 2 1]Nobody[e]

[msg ADACHI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Adachi is nearby.[n][f 1 1][e]

[msg AI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Ai is nearby.[n][f 1 1][e]

[msg CHIE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Chie is nearby.[n][f 1 1][e]

[msg DOJIMA_ALREADY_HERE]
[f 0 5 -258][f 2 1]Dojima is nearby.[n][f 1 1][e]

[msg AYANE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Ayane is nearby.[n][f 1 1][e]

[msg YUMI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yumi is nearby.[n][f 1 1][e]

[msg BUS_ALREADY_HERE]
[f 0 5 -258][f 2 1]The bus stop is nearby.[n][f 1 1][e]

[msg HISANO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Hisano is nearby.[n][f 1 1][e]

[msg KANJI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Kanji is nearby.[n][f 1 1][e]

[msg MARIE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Marie is nearby.[n][f 1 1][e]

[msg NANAKO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Nanako is nearby.[n][f 1 1][e]

[msg NAOKI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Naoki is nearby.[n][f 1 1][e]

[msg NAOTO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Naoto is nearby.[n][f 1 1][e]

[msg RISE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Rise is nearby.[n][f 1 1][e]

[msg KOU_ALREADY_HERE]
[f 0 5 -258][f 2 1]Kou is nearby.[n][f 1 1][e]

[msg DAISUKE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Daisuke is nearby.[n][f 1 1][e]

[msg YOSUKE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yosuke is nearby.[n][f 1 1][e]

[msg YUKIKO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yukiko is nearby.[n][f 1 1][e]

[msg SHRINE_ALREADY_HERE]
[f 0 5 -258][f 2 1]The shrine is nearby.[n][f 1 1][e]

[msg TEDDIE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Teddie is nearby.[n][f 1 1][e]