[msg HANGOUT_MSG]
[f 0 5 -258][f 2 1]Who do you want to see?[n][f 1 1][e]

[sel HANG_OUT_SEL]
[f 0 5 -258][f 2 1]Adachi (Lvl [f 2 4 16][f 2 4 0])[e]
[f 0 5 -258][f 2 1]Ai (Lvl [f 2 4 17][f 2 4 1])[e]
[f 0 5 -258][f 2 1]Ayane (Lvl [f 2 4 19][f 2 4 3])[e]
[f 0 5 -258][f 2 1]Chie (Lvl [f 2 4 18][f 2 4 2])[e]
[f 0 5 -258][f 2 1]Daisuke (Lvl [f 2 4 29][f 2 4 13])[e]
[f 0 5 -258][f 2 1]Dojima (Lvl [f 2 4 29][f 2 4 13])[e]
[f 0 5 -258][f 2 1]Eri (Lvl [f 2 4 20][f 2 4 4])[e]
[f 0 5 -258][f 2 1]Hisano (Lvl [f 2 4 21][f 2 4 5])[e]
[f 0 5 -258][f 2 1]Kanji (Lvl [f 2 4 22][f 2 4 6])[e]
[f 0 5 -258][f 2 1]Kou (Lvl [f 2 4 29][f 2 4 13])[e]
[f 0 5 -258][f 2 1]Marie (Lvl [f 2 4 23][f 2 4 7])[e]
[f 0 5 -258][f 2 1]Nanako (Lvl [f 2 4 21][f 2 4 5])[e]
[f 0 5 -258][f 2 1]Naoki (Lvl [f 2 4 24][f 2 4 8])[e]
[f 0 5 -258][f 2 1]Naoto (Lvl [f 2 4 25][f 2 4 9])[e]
[f 0 5 -258][f 2 1]Rise (Lvl [f 2 4 26][f 2 4 10])[e]
[f 0 5 -258][f 2 1]Sayoko (Lvl [f 2 4 27][f 2 4 11])[e]
[f 0 5 -258][f 2 1]Shu (Lvl [f 2 4 28][f 2 4 12])[e]
[f 0 5 -258][f 2 1]Yosuke (Lvl [f 2 4 30][f 2 4 14])[e]
[f 0 5 -258][f 2 1]Yukiko (Lvl [f 2 4 31][f 2 4 15])[e]
[f 0 5 -258][f 2 1]Yumi (Lvl [f 2 4 19][f 2 4 3])[e]
[f 0 5 -258][f 2 1]Others...[e]
[f 0 5 -258][f 2 1]Cancel[e]

[msg ADACHI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Adachi is already nearby.[n][f 1 1][e]

[msg AI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Ai is already nearby.[n][f 1 1][e]

[msg CHIE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Chie is already nearby.[n][f 1 1][e]

[msg DOJIMA_ALREADY_HERE]
[f 0 5 -258][f 2 1]Dojima is already nearby.[n][f 1 1][e]

[msg AYANE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Ayane is already nearby.[n][f 1 1][e]

[msg YUMI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yumi is already nearby.[n][f 1 1][e]

[msg BUS_ALREADY_HERE]
[f 0 5 -258][f 2 1]The bus stop is already nearby.[n][f 1 1][e]

[msg HISANO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Hisano is already nearby.[n][f 1 1][e]

[msg KANJI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Kanji is already nearby.[n][f 1 1][e]

[msg MARIE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Marie is already nearby.[n][f 1 1][e]

[msg NANAKO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Nanako is already nearby.[n][f 1 1][e]

[msg NAOKI_ALREADY_HERE]
[f 0 5 -258][f 2 1]Naoki is already nearby.[n][f 1 1][e]

[msg NAOTO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Naoto is already nearby.[n][f 1 1][e]

[msg RISE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Rise is already nearby.[n][f 1 1][e]

[msg KOU_ALREADY_HERE]
[f 0 5 -258][f 2 1]Kou is already nearby.[n][f 1 1][e]

[msg DAISUKE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Daisuke is already nearby.[n][f 1 1][e]

[msg YOSUKE_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yosuke is already nearby.[n][f 1 1][e]

[msg YUKIKO_ALREADY_HERE]
[f 0 5 -258][f 2 1]Yukiko is already nearby.[n][f 1 1][e]