[msg ESCAPE_BAN]
[f 0 5 -258][f 2 1]> Something is preventing it from[n]working...[n][f 1 1][e]

[msg ConfirmGohomRise [Rise]]
[f 0 5 -258][f 2 1]Use a Goho-M/Return Daikon and return to the entrance?[n][e]

[msg ConfirmGohomTeddie [Teddie]]
[f 0 5 -258][f 2 1]Use a Goho-M/Return Daikon and return to the entrance?[n][e]

[msg NoMoreRise [Rise]]
[f 0 5 -258][f 2 1]Looks like you're all out, Senpai.[n]Let's find another way back.[n][f 1 1][e]

[msg NoMoreTeddie [Teddie]]
[f 0 5 -258][f 2 1]Wahhh... Sensei, your Goho-M[n]stash is looking bear![n][f 1 1][e]

