[sel PartySel]
[f 0 5 -258][f 2 1]Yosuke[e]
[f 0 5 -258][f 2 1]Chie[e]
[f 0 5 -258][f 2 1]Yukiko[e]
[f 0 5 -258][f 2 1]Kanji[e]
[f 0 5 -258][f 2 1]Naoto[e]
[f 0 5 -258][f 2 1]Teddie[e]
[f 0 5 -258][f 2 1]Cancel[e]

[sel OptionSel]
[f 0 5 -258][f 2 1]Add member[e]
[f 0 5 -258][f 2 1]Remove member[e]
[f 0 5 -258][f 2 1]Finish[e]

[msg SelectMemberMsg]
[f 0 5 -258][f 2 1]Add which member?[e]

[msg ReplaceMemberMsg]
[f 0 5 -258][f 2 1]Replace which member?[e]

[msg RemoveMemberMsg]
[f 0 5 -258][f 2 1]Remove which member?[e]

[msg OptionMsg]
[f 0 5 -258][f 2 1]What will you do?[e]

[sel TOMB_SEL_HOOK]
[f 0 5 -258][f 2 1]Return to the entrance[e]
[f 0 5 -258][f 2 1]Organize party[e]
[f 0 5 -258][f 2 1]Daidara[e]
[f 0 5 -258][f 2 1]Shiroku Store[e]
[f 0 5 -258][f 2 1]Velvet Room[e]
[f 0 5 -258][f 2 1]Go back home[e]
[f 0 5 -258][f 2 1]Cancel[e]

[sel LIQUEUR_SEL_HOOK]
[f 0 5 -258][f 2 1]Return to the entrance[e]
[f 0 5 -258][f 2 1]Organize party[e]
[f 0 5 -258][f 2 1]Cancel[e]