[msg Square_Menu_Text]
[f 0 5 -258][f 2 1]What will you do?[n][f 1 1][e]

[sel Square_Menu]
[f 0 5 -258][f 2 1]Quick travel[e]
[f 0 5 -258][f 2 1]Save[e]
[f 0 5 -258][f 2 1]Mod menu[e]
[f 0 5 -258][f 2 1]Options[e]

[sel Square_Menu_Dng]
[f 0 5 -258][f 2 1]Dungeon options[e]
[f 0 5 -258][f 2 1]Save[e]
[f 0 5 -258][f 2 1]Mod menu[e]
[f 0 5 -258][f 2 1]Options[e]

[msg Mod_Menu_Text]
[f 0 5 -258][f 2 1]P4G Mod Menu[n][f 1 1][e]

[sel Mod_Menu]
[f 0 5 -258][f 2 1]Call Menu[e]
[f 0 5 -258][f 2 1]Player Menu[e]
[f 0 5 -258][f 2 1]Flags[e]

[sel ModPartySel]
[f 0 5 -258][f 2 1]Yosuke[e]
[f 0 5 -258][f 2 1]Chie[e]
[f 0 5 -258][f 2 1]Yukiko[e]
[f 0 5 -258][f 2 1]Kanji[e]
[f 0 5 -258][f 2 1]Naoto[e]
[f 0 5 -258][f 2 1]Teddie[e]
[f 0 5 -258][f 2 1]Quit[e]

[sel ModOptionSel]
[f 0 5 -258][f 2 1]Add member[e]
[f 0 5 -258][f 2 1]Remove member[e]
[f 0 5 -258][f 2 1]Cancel[e]

[msg ModSelectMemberMsg]
[f 0 5 -258][f 2 1]Add which member?[e]

[msg ModReplaceMemberMsg]
[f 0 5 -258][f 2 1]Replace which member?[e]

[msg ModRemoveMemberMsg]
[f 0 5 -258][f 2 1]Remove which member?[e]

[msg ModOptionMsg]
[f 0 5 -258][f 2 1]What will you do?[e]

[msg Call_Menu_Text]
[f 0 5 -258][f 2 1]Call Menu (Page 1)[n][f 1 1][e]

[sel Call_Menu_1]
[f 0 5 -258][f 2 1]Call Field[e]
[f 0 5 -258][f 2 1]Call Event[e]
[f 0 5 -258][f 2 1]Call Facility[e]
[f 0 5 -258][f 2 1]Call Battle[e]
[f 0 5 -258][f 2 1]Call Floor[e]

[msg Call_Menu_Text_2]
[f 0 5 -258][f 2 1]Call Menu (Page 2)[n][f 1 1][e]

[sel Call_Menu_2]
[f 0 5 -258][f 2 1]Call Dungeon[e]
[f 0 5 -258][f 2 1]Call Cutscene[e]
[f 0 5 -258][f 2 1]Play Credits[e]
[f 0 5 -258][f 2 1]Call BGM[e]
[f 0 5 -258][f 2 1]Call SFX[e]

[msg Player_Menu_Text_1]
[f 0 5 -258][f 2 1]Player Menu (Page 1)[n][f 1 1][e]

[msg Player_Menu_Text_2]
[f 0 5 -258][f 2 1]Player Menu (Page 2)[n][f 1 1][e]

[sel Player_Menu_1]
[f 0 5 -258][f 2 1]Change Name[e]
[f 0 5 -258][f 2 1]Change Date[e]
[f 0 5 -258][f 2 1]Change Yen[e]
[f 0 5 -258][f 2 1]Change Items[e]
[f 0 5 -258][f 2 1]Loop Current Day[e]

[sel Player_Menu_2]
[f 0 5 -258][f 2 1]Social Links[e]
[f 0 5 -258][f 2 1]Social Stats[e]
[f 0 5 -258][f 2 1]Party Members[e]
[f 0 5 -258][f 2 1]Refill HP/SP[e]

[msg Facility_Menu_Text]
[f 0 5 -258][f 2 1]Facility Menu (Page 1)[n][f 1 1][e]

[msg Facility_Menu_Text_2]
[f 0 5 -258][f 2 1]Facility Menu (Page 2)[n][f 1 1][e]

[sel Facility_Menu_1]
[f 0 5 -258][f 2 1]TV Studio[e]
[f 0 5 -258][f 2 1]Town Map[e]
[f 0 5 -258][f 2 1]Daidara's Shop[e]
[f 0 5 -258][f 2 1]Shiroku Shop[e]
[f 0 5 -258][f 2 1]Shiroku Pub[e]

[sel Facility_Menu_2]
[f 0 5 -258][f 2 1]Velvet Room[e]
[f 0 5 -258][f 2 1]Junes Foodcourt[e]
[f 0 5 -258][f 2 1]Crocofur[e]
[f 0 5 -258][f 2 1]Book Shop[e]
[f 0 5 -258][f 2 1]Produce Shop[e]

[msg Flag_Menu_Text]
[f 0 5 -258][f 2 1]Flag Menu[n][f 1 1][e]

[sel Flag_Menu]
[f 0 5 -258][f 2 1]Edit Flag[e]
[f 0 5 -258][f 2 1]Mass Flag Edit[e]
[f 0 5 -258][f 2 1]Complete All Quests[e]
[f 0 5 -258][f 2 1]Renew All Quests[e]
[f 0 5 -258][f 2 1]Turn Off Tired Flags[e]
[f 0 5 -258][f 2 1]Unlock Entire Town Map[e]
[f 0 5 -258][f 2 1]Toggle Menu Options[e]

[sel OnOff]
[f 0 5 -258][f 2 1]On[e]
[f 0 5 -258][f 2 1]Off[e]

[sel PlusOrMinus]
[f 0 5 -258][f 2 1]+[e]
[f 0 5 -258][f 2 1]-[e]

[msg Operation]
[f 0 5 -258][f 2 1]Which sign?[n][f 1 1][e]

[msg SS_Menu_Text]
[f 0 5 -258][f 2 1]Social Stats Menu[n][f 1 1][e]

[sel SS_Menu]
[f 0 5 -258][f 2 1]Courage[e]
[f 0 5 -258][f 2 1]Knowledge[e]
[f 0 5 -258][f 2 1]Diligence[e]
[f 0 5 -258][f 2 1]Understanding[e]
[f 0 5 -258][f 2 1]Expression[e]
[f 0 5 -258][f 2 1]Max all stats[e]

[msg SL_Menu_Text]
[f 0 5 -258][f 2 1]Social Link Menu[n][f 1 1][e]

[sel SL_Menu]
[f 0 5 -258][f 2 1]Level Up SL[e]
[f 0 5 -258][f 2 1]Reverse SL[e]
[f 0 5 -258][f 2 1]Break SL[e]
[f 0 5 -258][f 2 1]Change SL[e]
[f 0 5 -258][f 2 1]Add SL[e]

[msg BATTLE_SEL_Text]
[f 0 5 -258][f 2 1]Battle Menu[n][f 1 1][e]

[sel BATTLE_SEL]
[f 0 5 -258][f 2 1]Manual Input[e]
[f 0 5 -258][f 2 1]Boss Select[e]

[msg BOSS_SEL1_Text]
[f 0 5 -258][f 2 1]Boss Select (Page 1)[n][f 1 1][e]

[sel BOSS_SEL1]
[f 0 5 -258][f 2 1]Shadow Yosuke[e]
[f 0 5 -258][f 2 1]Shadow Chie[e]
[f 0 5 -258][f 2 1]Shadow Yukiko[e]
[f 0 5 -258][f 2 1]Shadow Kanji[e]
[f 0 5 -258][f 2 1]Shadow Rise[e]
[f 0 5 -258][f 2 1]Shadow Teddie[e]
[f 0 5 -258][f 2 1]Shadow Mitsuo[e]

[msg BOSS_SEL2_Text]
[f 0 5 -258][f 2 1]Boss Select (Page 2)[n][f 1 1][e]

[sel BOSS_SEL2]
[f 0 5 -258][f 2 1]Shadow Naoto[e]
[f 0 5 -258][f 2 1]Namatame[e]
[f 0 5 -258][f 2 1]Adachi[e]
[f 0 5 -258][f 2 1]Ameno-Sagiri[e]
[f 0 5 -258][f 2 1]Kusumi-no-Okami[e]
[f 0 5 -258][f 2 1]Izanami[e]
[f 0 5 -258][f 2 1]Margaret[e]

