[sel Num_Menu]
[f 0 5 -258][f 2 1]0[e]
[f 0 5 -258][f 2 1]1[e]
[f 0 5 -258][f 2 1]2[e]
[f 0 5 -258][f 2 1]3[e]
[f 0 5 -258][f 2 1]4[e]

[sel Num_Menu2]
[f 0 5 -258][f 2 1]5[e]
[f 0 5 -258][f 2 1]6[e]
[f 0 5 -258][f 2 1]7[e]
[f 0 5 -258][f 2 1]8[e]
[f 0 5 -258][f 2 1]9[e]

[sel OnOff_Text]
[f 0 5 -258][f 2 1]Toggle[e]

[sel OnOff]
[f 0 5 -258][f 2 1]On[e]
[f 0 5 -258][f 2 1]Off[e]
[f 0 5 -258][f 2 1]Cancel[e]

[msg MSG_1]
[f 0 5 -258][f 2 1]1 Digit[n][f 1 1][e]

[msg MSG_2]
[f 0 5 -258][f 2 1]2 Digits[n][f 1 1][e]

[msg MSG_1_Bytes]
[f 0 5 -258][f 2 1]1 Digit (Number of Bytes)[n][f 1 1][e]

[msg MSG_2_Day]
[f 0 5 -258][f 2 1]2 Digits (Day)[n][f 1 1][e]

[msg MSG_3]
[f 0 5 -258][f 2 1]3 Digits[n][f 1 1][e]

[msg MSG_4]
[f 0 5 -258][f 2 1]4 Digits[n][f 1 1][e]

[msg MSG_5]
[f 0 5 -258][f 2 1]5 Digits[n][f 1 1][e]

[msg MSG_1_Major]
[f 0 5 -258][f 2 1]1 Digit (Major)[n][f 1 1][e]

[msg MSG_2_Major]
[f 0 5 -258][f 2 1]2 Digits (Major)[n][f 1 1][e]

[msg MSG_3_Major]
[f 0 5 -258][f 2 1]3 Digits (Major)[n][f 1 1][e]

[msg MSG_4_Major]
[f 0 5 -258][f 2 1]4 Digits (Major)[n][f 1 1][e]

[msg MSG_4_Item]
[f 0 5 -258][f 2 1]4 Digits (Item)[n][f 1 1][e]

[msg InvalidItem]
[f 0 5 -258][f 2 1]Invalid number! Choose value under 2560.[n][f 1 1][e]

[msg MSG_2_Item]
[f 0 5 -258][f 2 1]2 Digits (#Items)[n][f 1 1][e]

[msg MSG_5_Major]
[f 0 5 -258][f 2 1]5 Digits (Major)[n][f 1 1][e]

[msg MSG_1_Minor]
[f 0 5 -258][f 2 1]1 Digit (Minor)[n][f 1 1][e]

[msg MSG_2_Minor]
[f 0 5 -258][f 2 1]2 Digits (Minor)[n][f 1 1][e]

[msg MSG_3_Minor]
[f 0 5 -258][f 2 1]3 Digits (Minor)[n][f 1 1][e]

[msg MSG_4_Minor]
[f 0 5 -258][f 2 1]4 Digits (Minor)[n][f 1 1][e]

[msg MSG_5_Minor]
[f 0 5 -258][f 2 1]5 Digits (Minor)[n][f 1 1][e]

[msg MSG_9_Location]
[f 0 5 -258][f 2 1]9 Digits (Location)[n][f 1 1][e]

[msg MSG_6]
[f 0 5 -258][f 2 1]6 Digits[n][f 1 1][e]

[msg MSG_7]
[f 0 5 -258][f 2 1]7 Digits (Yen)[n][f 1 1][e]

[msg ConfirmNumber]
[f 0 5 -258][f 2 1]Confirm [f 2 4 0] as selection?[n][e]

[sel ConfirmCancel]
[f 0 5 -258][f 2 1]Confirm[e]
[f 0 5 -258][f 2 1]Cancel[e]

[msg ConfirmItem]
[f 0 5 -258][f 2 1]Selected item: [f 2 5 3 -1 0] × [f 2 4 1][e]