[msg SquareMenuConfig]
[f 0 5 -258][f 2 1][f 0 1 1]Custom Sub Menu Setup[n]
[f 0 1 0]Thanks for trying the Custom Sub Menu mod!
[n]Please choose which features you'd like to use.
[n]You can always change these settings later.[f 1 1][e]

[sel ToggleMenu]
[f 0 5 -258][f 2 1]On[e]
[f 0 5 -258][f 2 1]Off[e]
[f 0 5 -258][f 2 1]Cancel[e]

[sel YesNo]
[f 0 5 -258][f 2 1]Yes[e]
[f 0 5 -258][f 2 1]No[e]

[msg SquareMenuOptions_Text]
[f 0 5 -258][f 2 1]Options (1/2 Press Back to Exit)[f 1 1][e]

[msg SquareMenuOptions_Text_2]
[f 0 5 -258][f 2 1]Options (2/2 Press Back to Exit)[f 1 1][e]

[sel SquareMenuOptions]
[f 0 5 -258][f 2 1]Mod Menu: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Quick Travel Plus: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Mobile Calendar: [f 2 4 2][e]
[f 0 5 -258][f 2 1]Dungeon Options: [f 2 4 3][e]
[f 0 5 -258][f 2 1]Find A Friend: [f 2 4 4][e]
[f 0 5 -258][f 2 1]Save Anywhere: [f 2 4 5][e]
[f 0 5 -258][f 2 1]Game Over Skip: [f 2 4 6][e]
[f 0 5 -258][f 2 1]Reap-Balanced Encounters: [f 2 4 7][e]
[f 0 5 -258][f 2 1]Default Direct Commands: [f 2 4 8][e]
[f 0 5 -258][f 2 1]Remove Events: [f 2 4 9][e]
[f 0 5 -258][f 2 1]Save Everyday: [f 2 4 10][e]
[f 0 5 -258][f 2 1]Next[e]
[f 0 5 -258][f 2 1]Previous[e]

[msg OptionsWarning]
[f 0 5 -258][f 2 1]Access the Options Menu again by pressing
[n]the [f 0 1 2]Command Menu button[f 0 1 0] from the top level
[n]of the Sub Menu.[f 1 1][e]

[msg ModMenu_About[Mod Menu (Sierra/ShrineFox)]]
[f 0 5 -258][f 2 1]A powerful tool for modders. Enables options for
[n]calling of fields and events, toggling of flags,
[n]stat editing and much more. Use with caution![e]

[msg QuickTravelPlus_About[Quick Travel Plus (ShrineFox)]]
[f 0 5 -258][f 2 1]A quality of life tweak inspired by Persona 5. Expands 
[n]the fast travel menus (sub menu and map) with more
[n]locations for improved overworld traversal.[e]

[msg MobileCalendar_About[Mobile Calendar (ShrineFox)]]
[f 0 5 -258][f 2 1]Allows you to view the calendar from anywhere via
[n]an additional sub menu option. Best used with the
[n]"Useful Calendar" mod as a quality of life tweak.[e]

[msg DungeonOptions_About[Dungeon Options (Tekka)]]
[f 0 5 -258][f 2 1]Configurable quality of life tweaks for dungeon
[n]exploration. Includes rudiger's "Dungeon Text
[n]Fixes". Enable to view the available options.[e]

[msg FindAFriend_About[FindAFriend (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]A quality of life tweak to make keeping track of
[n]Social Links less tedious. Adds a sub menu option
[n]to fast travel to their location when available.[e]

[msg SaveAnywhere_About[Save Anywhere (Tupelov)]]
[f 0 5 -258][f 2 1]Save your game from anywhere, straight from the sub
[n]menu. Normally, you would only be able to save from
[n]designated areas marked by the blue butterflies.[e]

[msg GameOverskip_About[Game Over Skip (Tekka)]]
[f 0 5 -258][f 2 1]When enabled, the Velvet Room scene with scrolling
[n]text will be skipped should you die. You will be
[n]asked instantly whether you would like to retry.[e]

[msg ConsistentReaper_About[Reap-Balanced Encounters (Tekka)]]
[f 0 5 -258][f 2 1]A quality of life tweak to remove the randomness
[n]from Reaper encounters. The 22nd chest opened will
[n]always contain a Reaper. Change floor to reset.[e]

[msg DirectCommands_About[Default Direct Commands (Tekka)]]
[f 0 5 -258][f 2 1]When enabled, party member tactics will be set to
[n]"Direct Commands" by default, saving you the time
[n]spent changing it yourself.[e]

[msg RemoveEvents_About[Remove Events (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Remove the Hot Springs, Camping Trip, Culture 
[n]Festival etc. If "On", you can configure each
[n]event individually to suit your preferences.[e]

[msg SaveEveryday_About[Save Everyday (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]If "On", you will be presented with the save prompt
[n]automatically at the beginning of every day.[e]

[msg RemoveEventsOptions_Text]
[f 0 5 -258][f 2 1]Remove Events Options[e]

[sel RemoveEventsOptions]
[f 0 5 -258][f 2 1]Remove Camping Trip: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Remove Cross Dressing: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Remove Group Date Cafe: [f 2 4 2][e]
[f 0 5 -258][f 2 1]Remove Hotsprings Event: [f 2 4 3][e]
[f 0 5 -258][f 2 1]Done[e]

[msg RemoveCamping_About[Camping (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Remove the entire camping trip.[e]

[msg RemoveCrossDress_About[Cross Dressing (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Remove the cross dressing competition
[n]from the culture festival.[e]

[msg RemoveGroupDate_About[Group Date (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Remove the group date cafe
[n]from the cultre festival.[e]

[msg RemoveHotsprings_About[Hotsprings (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Remove the hotsprings event where
[n]the guys get abused.[e]

[msg DungeonOptions_Text]
[f 0 5 -258][f 2 1]Dungeon Options[e]

[sel DungeonOptions]
[f 0 5 -258][f 2 1]Show Fox: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Show Floor Select: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Show Goho-M: [f 2 4 2][e]
[f 0 5 -258][f 2 1]Show Organize Party: [f 2 4 3][e]
[f 0 5 -258][f 2 1]Done[e]

[msg ShowFox_About[Fox Option (Tekka)]]
[f 0 5 -258][f 2 1]Allows you to purchase healing from the Fox
[n]anywhere via an additional sub menu option.
[n]Normally you would need to return to the entrance.[e]

[msg FloorSelect_About[Floor Select (Tekka)]]
[f 0 5 -258][f 2 1]A quality of life tweak activated after a dungeon's
[n]deadline. Allows you to fast travel to any floor,
[n]making future visits for quests less tedious.[e]

[msg GohoM_About[Goho-M Option (Tekka)]]
[f 0 5 -258][f 2 1]A quality of life tweak inspired by Persona 5.
[n]Adds a sub menu option that allows you to use
[n]Goho-M's quickly, without searching your items.[e]

[msg OrganizeParty_About[Organize Party (Tekka)]]
[f 0 5 -258][f 2 1]A quality of life tweak that allows you to swap
[n]party members via a new sub menu option without
[n]needing to leave a dungeon.[e]

[msg FindAFriendOptions_Text]
[f 0 5 -258][f 2 1]Find A Friend Options[e]

[sel FindAFriendOptions]
[f 0 5 -258][f 2 1]Spoiler-Free Mode: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Remove Invites: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Done[e]

[msg SPOILER_TOGGLE[FindAFriend (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]If "On", only Social Links you have discovered
[n]and initiated Rank 1 with will be shown.[e]

[msg RemoveInvitations_About[Remove Invites (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Removes the redundant lunchtime invitation scenes
[n]that play when a Social Link is available to rank-up.
[n]It's recommended to enable this with "Find a Friend".[e]

[msg IntroSkipConfig]
[f 0 5 -258][f 2 1][f 0 1 1]Prologue Skip Setup[n]
[f 0 1 0]The opening events of Persona 4 Golden
[n]are notoriously long, spanning about 1 to 3
[n]hours before real gameplay begins.[f 1 1][e]

[msg IntroSkipSelection[Prologue Skip (ShrineFox)]]
[f 0 5 -258][f 2 1]Would you like to skip the story exposition
[n]and start from April 20? This is not recommended
[n]for first-time players.[f 1 1][e]

[msg ShowFoxOptions_Text]
[f 0 5 -258][f 2 1]Show Fox Option[e]

[sel ShowFoxOptions]
[f 0 5 -258][f 2 1]Use Goho-M: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Done[e]

[msg ShowFox_GohoM[Fox Goho-M (Tekka)]]
[f 0 5 -258][f 2 1]A tweak designed to improve balance. If "On", 
[n]calling the fox will additionally require 
[n]a [f 2 5 3 -1 2] or [f 2 5 3 -1 3].[e]