[msg SquareMenuConfig[Square Menu Setup]]
[f 0 5 -258][f 2 1]Thanks for trying the Custom Square Menu mod!
[n]Please choose which features you'd like to use.
[n]You can always change these settings later.[f 1 1][e]

[sel ToggleMenu]
[f 0 5 -258][f 2 1]On[e]
[f 0 5 -258][f 2 1]Off[e]
[f 0 5 -258][f 2 1]Back...[e]

[sel YesNo]
[f 0 5 -258][f 2 1]Yes[e]
[f 0 5 -258][f 2 1]No[e]

[msg SquareMenuOptions_Text]
[f 0 5 -258][f 2 1]Square Menu Options[f 1 1][e]

[sel SquareMenuOptions]
[f 0 5 -258][f 2 1]Mod Menu: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Quick Travel Plus: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Mobile Calendar: [f 2 4 2][e]
[f 0 5 -258][f 2 1]Dungeon Options: [f 2 4 3][e]
[f 0 5 -258][f 2 1]Find A Friend: [f 2 4 4][e]
[f 0 5 -258][f 2 1]Save Anywhere: [f 2 4 5][e]
[f 0 5 -258][f 2 1]Game Over Skip: [f 2 4 6][e]
[f 0 5 -258][f 2 1]Reap-Balanced Encounters: [f 2 4 7][e]
[f 0 5 -258][f 2 1]Done[e]

[msg OptionsToggle]
[f 0 5 -258][f 2 1]Hide Options menu from Square Menu?[f 1 1][e]

[msg ModMenu_About[Mod Menu (Sierra/ShrineFox)]]
[f 0 5 -258][f 2 1]Call fields, events, battles, BGM, SFX etc. from
[n]anywhere by entering IDs. Toggle flags, change
[n]Social Links, yen, items, and even party members.[f 1 1][e]

[msg QuickTravelPlus_About[Quick Travel Plus (ShrineFox)]]
[f 0 5 -258][f 2 1]Quick Travel to any area in Yasogami High while in 
[n]the building. Also extends options in the entire town
[n]of Inaba.[f 1 1][e]

[msg MobileCalendar_About[Mobile Calendar (ShrineFox)]]
[f 0 5 -258][f 2 1]Allows you to view the calendar from anywhere
[n]via the Square Menu. It's highly recommended to
[n]use this with rudiger_gb's Useful Calendar mod.[f 1 1][e]

[msg DungeonOptions_About[Dungeon Options (Tekka)]]
[f 0 5 -258][f 2 1]Add/remove party members without leaving the dungeon.
[n]Use your Goho-Ms straight from the square menu.
[n]Fast travel to any dungeon floor after its deadline.[f 1 1][e]

[msg FindAFriend_About[FindAFriend (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Instantly travel to the location of any available
[n]Social Links on a given day. This saves you from
[n]looking up their location or searching town.[f 1 1][e]

[msg SaveAnywhere_About[Save Anywhere (Tupelov)]]
[f 0 5 -258][f 2 1]Save your game from any field, straight from
[n]the square menu. Normally, you would have to save at
[n]designated areas marked by blue butterflies.[f 1 1][e]

[msg GameOverskip_About[Game Over Skip (Tekka)]]
[f 0 5 -258][f 2 1]Skip the Velvet Room scene after losing a battle.
[n]Instantly decide whether or not to retry.[f 1 1][e]

[msg ConsistentReaper_About[Reap-Balanced Encounters (Tekka)]]
[f 0 5 -258][f 2 1]Guarantees a Reaper encounter after every 22 chests
[n]you open while dungeon crawling. Normally, there's
[n]only a small chance of an encounter.[f 1 1][e]

[msg DungeonOptions_Text]
[f 0 5 -258][f 2 1]Dungeon Options[f 1 1][e]

[sel DungeonOptions]
[f 0 5 -258][f 2 1]Show Fox: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Show Floor Select: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Show Goho-M: [f 2 4 2][e]
[f 0 5 -258][f 2 1]Show Organize Party: [f 2 4 3][e]
[f 0 5 -258][f 2 1]Done[e]

[msg ShowFox_About[Fox Option (Tekka)]]
[f 0 5 -258][f 2 1]Adds the option to purchase healing from
[n]the fox at any point while dungeon crawling
[n]without having to leave the floor.[f 1 1][e]

[msg FloorSelect_About[Floor Select (Tekka)]]
[f 0 5 -258][f 2 1]Adds an option to instantly go to
[n]any floor in the dungeon while exploring it.
[n]Activates after the dungeon's deadline.[f 1 1][e]

[msg GohoM_About[Goho-M Option (Tekka)]]
[f 0 5 -258][f 2 1]Adds an option to instantly use
[n]a Goho-M from your inventory to exit the
[n]dungeon with ease.[f 1 1][e]

[msg OrganizeParty_About[Organize Party (Tekka)]]
[f 0 5 -258][f 2 1]Adds an option to swap party members
[n]on the fly while dungeon crawling. Reloads the
[n]floor you're currently on.[f 1 1][e]