[msg SquareMenuConfig]
[f 0 5 -258][f 2 1][f 0 1 1]Custom Sub Menu Setup[n]
[f 0 1 0]Thanks for trying the Custom Sub Menu mod!
[n]Please choose which features you'd like to use.
[n]You can always change these settings later.[f 1 1][e]

[sel ToggleMenu]
[f 0 5 -258][f 2 1]On[e]
[f 0 5 -258][f 2 1]Off[e]
[f 0 5 -258][f 2 1]Cancel[e]

[sel YesNo]
[f 0 5 -258][f 2 1]Yes[e]
[f 0 5 -258][f 2 1]No[e]

[msg SquareMenuOptions_Text]
[f 0 5 -258][f 2 1]Options (1/2 Press Back to Exit)[f 1 1][e]

[msg SquareMenuOptions_Text_2]
[f 0 5 -258][f 2 1]Options (2/2 Press Back to Exit)[f 1 1][e]

[sel SquareMenuOptions]
[f 0 5 -258][f 2 1]Mod Menu: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Quick Travel Plus: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Mobile Calendar: [f 2 4 2][e]
[f 0 5 -258][f 2 1]Dungeon Options: [f 2 4 3][e]
[f 0 5 -258][f 2 1]Find A Friend: [f 2 4 4][e]
[f 0 5 -258][f 2 1]Save Anywhere: [f 2 4 5][e]
[f 0 5 -258][f 2 1]Game Over Skip: [f 2 4 6][e]
[f 0 5 -258][f 2 1]Reap-Balanced Encounters: [f 2 4 7][e]
[f 0 5 -258][f 2 1]Default Direct Commands: [f 2 4 8][e]
[f 0 5 -258][f 2 1]Remove Events: [f 2 4 9][e]
[f 0 5 -258][f 2 1]Save Everyday: [f 2 4 10][e]
[f 0 5 -258][f 2 1]Next[e]
[f 0 5 -258][f 2 1]Previous[e]

[msg OptionsWarning]
[f 0 5 -258][f 2 1]Access the Options Menu again by pressing
[n]the [f 0 1 2]Command Menu button[f 0 1 0] in the top level
[n]of the Sub Menu.[f 1 1][e]

[msg ModMenu_About[Mod Menu (Sierra/ShrineFox)]]
[f 0 5 -258][f 2 1]Call fields, events, battles, BGM, SFX etc. from
[n]anywhere by entering IDs. Toggle flags, change
[n]Social Links, yen, items, and even party members.[e]

[msg QuickTravelPlus_About[Quick Travel Plus (ShrineFox)]]
[f 0 5 -258][f 2 1]Quick Travel to any area in Yasogami High while in 
[n]the building. Also extends options in the entire town
[n]of Inaba.[e]

[msg MobileCalendar_About[Mobile Calendar (ShrineFox)]]
[f 0 5 -258][f 2 1]Allows you to view the calendar from anywhere
[n]via the Square Menu. It's highly recommended to
[n]use this with rudiger_gb's Useful Calendar mod.[e]

[msg DungeonOptions_About[Dungeon Options (Tekka)]]
[f 0 5 -258][f 2 1]Add/remove party members without leaving the dungeon.
[n]Use your Goho-Ms straight from the square menu.
[n]Fast travel to any dungeon floor after its deadline.[e]

[msg FindAFriend_About[FindAFriend (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Instantly travel to the location of any available
[n]Social Links on a given day. This saves you from
[n]looking up their location or searching town.[e]

[msg SaveAnywhere_About[Save Anywhere (Tupelov)]]
[f 0 5 -258][f 2 1]Save your game from any field, straight from
[n]the square menu. Normally, you would have to save at
[n]designated areas marked by blue butterflies.[e]

[msg GameOverskip_About[Game Over Skip (Tekka)]]
[f 0 5 -258][f 2 1]Skip the Velvet Room scene after losing a battle.
[n]Instantly decide whether or not to retry.[e]

[msg ConsistentReaper_About[Reap-Balanced Encounters (Tekka)]]
[f 0 5 -258][f 2 1]Guarantees a Reaper encounter after every 22 chests
[n]you open while dungeon crawling. Normally, there's
[n]only a small chance of an encounter.[e]

[msg DirectCommands_About[Default Direct Commands (Tekka)]]
[f 0 5 -258][f 2 1]Automatically sets party member tactics to Direct
[n]Commands so you don't have to take the couple
[n]seconds to change it yourself.[e]

[msg RemoveEvents_About[Remove Events (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Removes the Hot Springs, Camping Trip and
[n]Culture Festival. Each of these events can be  
[n]individually disabled to fit your preferences.[e]

[msg SaveEveryday_About[Save Everyday (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Shows the save prompt at the beginning
[n]of everyday. [e]

[msg RemoveEventsOptions_Text]
[f 0 5 -258][f 2 1]Remove Events Options[e]

[sel RemoveEventsOptions]
[f 0 5 -258][f 2 1]Remove Camping Trip: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Remove Cross Dressing: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Remove Group Date Cafe: [f 2 4 2][e]
[f 0 5 -258][f 2 1]Remove Hotsprings Event: [f 2 4 3][e]
[f 0 5 -258][f 2 1]Done[e]

[msg RemoveCamping_About[Camping (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Remove the entire camping trip.[e]

[msg RemoveCrossDress_About[Cross Dressing (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Remove the cross dressing competition
[n]from the culture festival.[e]

[msg RemoveGroupDate_About[Group Date (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Remove the group date cafe
[n]from the cultre festival.[e]

[msg RemoveHotsprings_About[Hotsprings (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Remove the hotsprings event where
[n]the guys get abused.[e]

[msg DungeonOptions_Text]
[f 0 5 -258][f 2 1]Dungeon Options[e]

[sel DungeonOptions]
[f 0 5 -258][f 2 1]Show Fox: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Show Floor Select: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Show Goho-M: [f 2 4 2][e]
[f 0 5 -258][f 2 1]Show Organize Party: [f 2 4 3][e]
[f 0 5 -258][f 2 1]Done[e]

[msg ShowFox_About[Fox Option (Tekka)]]
[f 0 5 -258][f 2 1]Adds the option to purchase healing from
[n]the fox at any point while dungeon crawling
[n]without having to leave the floor.[e]

[msg FloorSelect_About[Floor Select (Tekka)]]
[f 0 5 -258][f 2 1]Adds an option to instantly go to
[n]any floor in the dungeon while exploring it.
[n]Activates after the dungeon's deadline.[e]

[msg GohoM_About[Goho-M Option (Tekka)]]
[f 0 5 -258][f 2 1]Adds an option to instantly use
[n]a Goho-M from your inventory to exit the
[n]dungeon with ease.[e]

[msg OrganizeParty_About[Organize Party (Tekka)]]
[f 0 5 -258][f 2 1]Adds an option to swap party members
[n]on the fly while dungeon crawling. Reloads the
[n]floor you're currently on.[e]

[msg FindAFriendOptions_Text]
[f 0 5 -258][f 2 1]Find A Friend Options[e]

[sel FindAFriendOptions]
[f 0 5 -258][f 2 1]Spoiler-Free Mode: [f 2 4 0][e]
[f 0 5 -258][f 2 1]Remove Invites: [f 2 4 1][e]
[f 0 5 -258][f 2 1]Done[e]

[msg SPOILER_TOGGLE[FindAFriend (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Set spoiler-free mode
[n](Only social links you have met will be shown)[e]

[msg RemoveInvitations_About[Remove Invites (AnimatedSwine37)]]
[f 0 5 -258][f 2 1]Removes lunchtime invitations to spend time with a
[n]Social Link after school. It's highly recommended to 
[n]use this with Find a Friend.[e]

[msg IntroSkipConfig]
[f 0 5 -258][f 2 1][f 0 1 1]Prologue Skip Setup[n]
[f 0 1 0]The opening events of Persona 4 Golden
[n]are notoriously long, spanning about 1 to 3
[n]hours before real gameplay begins.[f 1 1][e]

[msg IntroSkipSelection[Prologue Skip (ShrineFox)]]
[f 0 5 -258][f 2 1]Would you like to skip the story exposition
[n]and start from April 20? This is not recommended
[n]for first-time players.[f 1 1][e]